spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

file:
  upload-dir: /taskapp/uploads

jwt:
  sign-key: secretsecretsecretsecretsecretsecret
  token-prefix: Bearer
  access-valid-time: 1
  issuer: Billing